### ISSUE TITLE
int(date.strftime("%s")) ValueError: Invalid format string

### ISSUE THREAD

**Issue by coglmn** [addisonlynch/pyTD#1]
Hello, thanks for sharing code. I did checkout your code and tried to run it. I am running it in Windows with Python 3.7. It seems strftime("%s") in windows is not supported. It raises the following error:

 File "C:\Users\git\pyTD\pyTD\utils\__init__.py", line 115, in to_timestamp
    return int(date.strftime("%s"))
ValueError: Invalid format string

I have replaced "%s" with "%S" and it seems to pass (proceeds from here without runtime error), though not sure if this is the correct replacement. Thought?

**Comment by addisonlynch** [comment]
I've updated this file for python 2.7 compatibility. It should now be working correctly with a different implementation which does not use ``strftime``.
