### ISSUE TITLE
Token authorization fails, though the authentication in the browser succeeds

### ISSUE THREAD

**Issue by coglmn** [addisonlynch/pyTD#2]
Hello, 

I have ran the code successfully, and after replacing the %s with %S in the first raised issue, now facing a token error with the following error load. I am running the code in Windows, and Python 3.7. 

Would you like to authorize a new refresh token? [y/n]: y
INFO - Starting authorization server
INFO - Opening browser to https://127.0.0.1:65010/td-callback
127.0.0.1 - - [11/Nov/2018 11:21:39] "GET /td-callback HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 11:21:39] "GET /style.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 11:21:39] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [11/Nov/2018 11:21:49] "GET /td-callback?code=fvlRg5....0B75E HTTP/1.1" 200 -
INFO - Shutting down authorization server
ERROR - Authorization could not be completed.
Traceback (most recent call last):
  File "C:\Users\git\pyTD\pyTD\auth\manager.py", line 89, in auth_via_browser
    refresh_token = tokens["refresh_token"]
KeyError: 'refresh_token'

Note that in the browser, I receive Success after entering username/pass. 

Appreciate any help.

**Comment by addisonlynch** [comment]
Hi @coglytic, apologies for my delay in response. I haven't had time to finish developing this package yet, but I am getting around to it now. I will look into your issue...I have been working to refactor the authorization engine entirely. 

Perhaps it is a windows issue...I haven't yet tested on Windows.

**Comment by addisonlynch** [comment]
@coglytic this has been repaired and is now live in the master branch.
